name: Android CI/CD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # Allows manual trigger from the Actions tab
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build APK
      run: ./gradlew assembleRelease
    - name: Upload to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        groups: testers # Change this to your group name in Firebase
        file: app/release/app-release.apk
