name: Firebase Distribution

on:
  push:
    branches:
      - main

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Verify APK Path
        run: ls -la app/release

      # Write Firebase credentials to a file
      - name: Write Firebase credentials to file
        run: echo "${{ secrets.FIREBASE_CREDENTIALS }}" > eventoriassignin-firebase-adminsdk-fbsvc-a7aa5e2e07.json

      # Check the Firebase credentials file to confirm it's written
      - name: Check Firebase credentials file
        run: cat eventoriassignin-firebase-adminsdk-fbsvc-a7aa5e2e07.json

      # Upload the APK to Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: eventoriassignin-firebase-adminsdk-fbsvc-a7aa5e2e07.json
          groups: "testers"
          file: "app/release/app-release.apk"
          releaseNotes: "Automated release from GitHub Actions"
          debug: true
